# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  
julia:
  - 1.3
  - nightly
  
matrix:
  allow_failures:
    - os: osx
    - julia: nightly
  
notifications:
  email: false
  
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.test("BHAtp"; coverage=true)'

after_success:

  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("BHAtp")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BHAtp")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
