authors = ["Rob J Goedman <goedman@mac.com>"]
name = "BHAtp"
uuid = "6583cbc6-6f1c-11e8-30da-a3ec7cc7062f"
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
